language: node_js
os: linux
dist: xenial
services: docker
node_js:
  - 12
env:
  - GRAKNURI=localhost:48556

before_script:
  - docker-compose --file docker-compose.test.yml up --detach --remove-orphans
  - while [ $(docker ps | wc -l) -ne 2 ]; do sleep 5; done

after_script:
  - docker-compose --file docker-compose.test.yml down
