version: '3'
services:
  master:
    build: .
    image: langleu/ma_crawler:latest
    ports:
      - '8000:8000'
    environment:
      TYPE: 'master'
      PORT: 8000
      GRAKNURI: 'grakn:48556'
      GITHUBACCOUNTS: '[{"username": "name", "token": "00000"}]'
    depends_on:
      - grakn
  
  node1:
    build: .
    image: langleu/ma_crawler:latest
    environment:
      TYPE: 'client'
      PORT: 8008
    depends_on:
      - master

  grakn:
    image: graknlabs/grakn:1.8.4
    ports:
      - '48556:48555'

  grakn-init:
    image: langleu/grakn-console:latest
    environment:
      ADDRESS: 'grakn:48555'
      KEYSPACE: 'docker'
      FILE: 'schema.gql'
    volumes:
      - './src/database/grakn/schema/schema.gql:/grakn/schema.gql'
    depends_on:
      - grakn
