define

  own sub relation,
    relates owner,
    relates ownee;
  
  contain sub relation,
    relates container,
    relates containment;

  include sub relation,
    relates inclusion,
    relates included;
  
  depend sub relates,
    relates dependant,
    relates dependency;

  user sub entity,
    plays owner,
    has rid,
    has name,
    has created,
    has updated,
    has platform,
    has schemaVersion;

  repository sub entity,
    plays ownee,
    plays container,
    has rid,
    has name,
    has fork,
    has created,
    has updated,
    has description,
    has schemaVersion;

  deployment sub entity,
    plays containment,
    plays inclusion,
    has rid,
    has rtype,
    has rawUrl,
    has name,
    has executable,
    has created,
    has updated,
    has version,
    has schemaVersion;

  service sub entity,
    plays included,
    plays dependant,
    plays dependency,
    has name,
    has rtype,
    has version,
    has created,
    has updated,
    has image,
    has metadata,
    has schemaVersion;

  rid sub attribute,
    datatype string;

  name sub attribute,
    datatype string;

  platform sub attribute,
    datatype string;

  fork sub attribute,
    datatype boolean;

  description sub attribute,
    datatype string;
  
  rtype sub attribute,
    datatype string;

  rawUrl sub attribute,
    datatype string;

  executable sub attribute,
    datatype long;

  version sub attribute,
    datatype string;

  created sub attribute,
    datatype datetime;

  updated sub attribute,
    datatype datetime;

  metadata sub attribute,
    datatype string;

  image sub attribute,
    datatype string;

  schemaVersion sub attribute,
    datatype long;
